// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACvTJiMhExY3Gkjhc852HAUGRAH-Tz1Ug',
    appId: '1:714920640805:web:4574c45a9d47c4b7e25acc',
    messagingSenderId: '714920640805',
    projectId: 'opero-644f7',
    authDomain: 'opero-644f7.firebaseapp.com',
    storageBucket: 'opero-644f7.firebasestorage.app',
    measurementId: 'G-EF2KFQGQWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVjs4zes9aHcXv2ecTM4zPUio6Cb1WxOE',
    appId: '1:714920640805:android:005094278b16b760e25acc',
    messagingSenderId: '714920640805',
    projectId: 'opero-644f7',
    storageBucket: 'opero-644f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMuP-M6M4MtY3CREIN4Mpefc2wKy3MGc',
    appId: '1:714920640805:ios:ad76fc3c98fdd8abe25acc',
    messagingSenderId: '714920640805',
    projectId: 'opero-644f7',
    storageBucket: 'opero-644f7.firebasestorage.app',
    iosBundleId: 'com.theviacoder.opero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwMuP-M6M4MtY3CREIN4Mpefc2wKy3MGc',
    appId: '1:714920640805:ios:ad76fc3c98fdd8abe25acc',
    messagingSenderId: '714920640805',
    projectId: 'opero-644f7',
    storageBucket: 'opero-644f7.firebasestorage.app',
    iosBundleId: 'com.theviacoder.opero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACvTJiMhExY3Gkjhc852HAUGRAH-Tz1Ug',
    appId: '1:714920640805:web:701f1ca1dc3e3bb7e25acc',
    messagingSenderId: '714920640805',
    projectId: 'opero-644f7',
    authDomain: 'opero-644f7.firebaseapp.com',
    storageBucket: 'opero-644f7.firebasestorage.app',
    measurementId: 'G-9MCXT0K0X3',
  );
}
